---
title: "Metadades"
author: "Julia Baguña Torres"
date: "2025-04-02"
output: html_document
---
# Metadades del conjunt de dades 2018-Phosphoproteomics 
#Source: https://github.com/nutrimetabolomics/metaboData/tree/main/Datasets/2018-Phosphoproteomics

## Descripció general

Aquest conjunt de dades s'ha obtingut a partir d'un experiment de fosfoproteòmica realitzat per analitzar (3 + 3) models PDX de dos subtipus de tumor diferents utilitzant mostres enriquides en fosfopèptids. L'anàlisi LC-MS (cromatografia líquida - espectrometria de masses) ha estat realitzada sobre dos replicats tècnics per cada mostra. Els valors de les abundàncies normalitzades dels senyals MS de ca. 1400 fosfopeptids han estat proporcionats.  

### Objectiu de l'anàlisi
L'objectiu d'aquest anàlisi és identificar fosfopèptids que permetin diferenciar els dos grups tumorals. Això es realitza mitjançant anàlisi estadístic, tècniques de visualització, reducció de dimensionalitat (PCA) i clustering.

## Estructura de les mostres

Les mostres es defineixen en dos grups: 

- MSS: Inclou les mostres M1, M5 i T49, cadascuna amb dos replicats tècnics.
- PD: Inclou les mostres M42, M43 i M64, també amb dos replicats tècnics per cada mostra.

## Descripció de les columnes del conjunt de dades

1. **SequenceModifications**: Descripció de la seqüència de fosfopèptids i les seves modificacions post-traduccionals.
   - Tipus: text
   
2. **Accession**: identificador del fosfopèptid/estudi.
   - Tipus: Cadenes de text  

3. **Description**: Descripció del fosfopèptid.
   - Tipus: text/numèric

4. **Score**: Qualitat de la mesura.
   - Tipus: Numèric
   
5-10. **M1_1_MSS, M1_2_MSS, M5_1_MSS, M5_2_MSS, T49_1_MSS, T49_2_MSS**: Abundància normalitzada de fosfopèptids per les mostres del grup MSS. Aquestes columnes mostren els dos replicats tècnics de cada mostra de l'individu (M1, M5, T49).
   - Tipus: Numèric 
   
11-16. **M42_1_PD, M42_2_PD, M43_1_PD, M43_2_PD, M64_1_PD, M64_2_PD**: Abundància normalitzada de fosfopèptids per les mostres del grup PD. Aquestes columnes mostren els dos replicats tècnics de cada mostra de l'individu (M42, M43, M64).
   - Tipus: Numèric 
   
17. **CLASS**: Classe del fosfopèptid.
    - Tipus: Factor 

18. **PHOSPHO**: Indica si el fosfopèptid està fosforilat o no.
    - Tipus: Factor 



